title: Wonkrew
logo: /assets/img/logo.png
description: Welcome on Wonkrew, A small busines iOS App developers.<br><br>Created by <a href="https://www.linkedin.com/in/farouk-gnandi/">Farouk GNANDI</a> long time iOS DEV and Apple addict for more than a decade.<br><br>Passionate traveller and blogger on <a href="https://www.journaldunvoyageur.fr/">A traveller diaries</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
